---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Values.podnotfound.labels.run }}
  name: {{ .Values.podnotfound.name }}
spec:
  containers:
  - image: {{ .Values.podnotfound.image }}
    name: {{ .Values.podnotfound.name }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Values.svcnotfound.labels.run }}
  name: {{ .Values.svcnotfound.name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: {{ .Values.podnotfound.labels.run }}
status:
  loadBalancer: {}