apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.deployment.app }}
  name: service-{{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.service.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Values.deployment.app }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}